# Generated by Django 3.2.23 on 2024-01-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('date_of_joining', models.DateField()),
                ('attendance_date', models.DateField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=False)),
            ],
        ),
    ]
